name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Install Graphviz
        run: sudo apt-get install -y graphviz
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Python script
        run: python hcs25.py > output.txt
      
      - name: Upload output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: hcs25-output
          path: hcs25-output.txt
