name: Run_my_python.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with the specific Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow graphviz  # Installs Pillow (for PIL) and graphviz Python packages

      - name: Install Tkinter (Ubuntu)
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Install Graphviz and Tkinter (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz  # Installs the system-level Graphviz binaries
          sudo apt-get install -y python3-tk  # Installs Tkinter

      - name: Set Env Var for CI
        run: 
           export CI=true
           echo $CI

      - name: Run Python script
        run: python hcs34-js2_ci.py
