name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Pillow graphviz  # Installs Pillow (for PIL) and graphviz Python packages

      - name: Install Graphviz and Tkinter (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz  # Installs the system-level Graphviz binaries
          sudo apt-get install -y python3-tk  # Installs Tkinter
      
      - name: Run Python script
        run: python hcs34-js2.py > output.txt
      
      - name: Upload output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: hcs34-js2-output
          path: hcs34-js2-output.txt
